### ISSUE TITLE
ELS Boost Schematic

### ISSUE THREAD

**Issue by JonWoellhaf** [vk3gs/Clough42#1]
Is a schematic for the ELS Boost board available?

**Comment by Johnboy251** [comment]
There is circuit details in part 8 about 2 mins 30sec in. 👍

**Comment by JonWoellhaf** [comment]
Thanks, Johnboy251. I don't know how I missed that part.

**Comment by JonWoellhaf** [comment]
The schematic is also available in Clough42's ELS CircuitMaker project. It was a HUGE hassle to sign up for CircuitMaker, but once I did I was able to get PDFs of the schematic and parts list.

**Comment by Johnboy251** [comment]
Hi JonWoellhaf. I must say I’ve had ‘trouble’ finding my way around GitHub but to get into this project that James has done such an amazing job, I’ll Just have to persevere.
